name: Test

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup toolchains
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall
      - name: Install dependencies
        run: sfw pnpm install --frozen-lockfile
      - name: Type-check
        run: pnpm typecheck
      - name: Biome check
        run: pnpm biome check
      - name: Syncpack lint
        run: pnpm syncpack lint
      - name: Syncpack format
        run: pnpm syncpack format --check
      - name: Checks for known security issues with the installed packages
        run: pnpm audit
      - name: Verify the package for publishing performing all checks and validations
        run: pnpm dlx jsr publish --dry-run
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup toolchains
        uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      - name: Setup Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall
      - name: Install Dependencies
        run: sfw pnpm install --frozen-lockfile
      - name: Run Tests
        run: pnpm vitest run --coverage --reporter=junit --outputFile=test-report.junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          use_oidc: true
          report_type: coverage
          files: coverage/coverage-final.json
          disable_search: true
          fail_ci_if_error: true
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        if: ${{ !cancelled() }}
        with:
          use_oidc: true
          report_type: test_results
          files: test-report.junit.xml
          disable_search: true
          fail_ci_if_error: true
  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
      - name: Type-check the dependencies
        run: deno check src/index.ts
