name: Test

on:
  workflow_call:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup toolchains
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - name: Setup Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall
      - name: Install dependencies
        run: sfw pnpm install
      - name: Biome check
        run: pnpm biome check
      - name: Syncpack lint
        run: pnpm syncpack lint
      - name: Syncpack format
        run: pnpm syncpack format --check
      - name: Checks for known security issues with the installed packages
        run: pnpm audit
      - name: Verify the package for publishing performing all checks and validations
        run: pnpm dlx jsr publish --dry-run
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup toolchains
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0
      - name: Setup Socket Firewall
        uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall
      - name: Install Dependencies
        run: sfw pnpm install
      - name: Run Tests
        run: pnpm vitest --coverage --reporter=junit --outputFile=test-report.junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
        with:
          use_oidc: true
      - name: Upload test results to Codecov
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1.2.1
        if: ${{ !cancelled() }}
        with:
          use_oidc: true
  deno:
    name: Deno
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install Deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
      - name: Type-check the dependencies
        run: deno check src/index.ts
